# Generated by Django 2.0.4 on 2018-04-10 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 4, 10, 14, 10, 27, 871508, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
